# Generated by Django 4.1.5 on 2023-04-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cont',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fund',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='loc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proj_profile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proj_stat',
            field=models.CharField(choices=[('Complete', 'On-Going')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='budg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agency',
            field=models.TextField(),
        ),migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.TextField(),
        ),migrations.AlterField(
            model_name='employee',
            name='reg',
            field=models.TextField(),
        ),migrations.AlterField(
            model_name='employee',
            name='cert',
            field=models.TextField(),
        ),migrations.AlterField(
            model_name='employee',
            name='reco',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
