# Generated by Django 4.1.5 on 2023-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_proj_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='proj_stat',
            field=models.CharField(choices=[('Complete', 'Complete'), ('On-Going', 'On-Going'), ('Under Procurement', 'Under Procurement')], max_length=20, null=True),
        ),
    ]
