# Generated by Django 4.1.5 on 2023-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employee_proj_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='proj_comment',
            field=models.TextField(default='No Comment', max_length=100),
        ),
    ]
