# Generated by Django 4.1.5 on 2023-04-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employee_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agency',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='budg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cert',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='progress',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reco',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reg',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slip',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
