# Generated by Django 4.1.5 on 2023-04-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_employee_agency_alter_employee_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='progress',
        ),
        migrations.AddField(
            model_name='employee',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cert',
            field=models.CharField(max_length=1000),
        ),
    ]
