# Generated by Django 4.1.5 on 2023-04-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_employee_budg_alter_employee_prog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='progress',
            new_name='progress',
        ),
    ]
