# Generated by Django 4.1.5 on 2023-04-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_employee_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slip',
            field=models.CharField(choices=[('ANS', 'ANS'), ('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending'), ('Terminated', 'Terminated'), ('Blanks', 'Blanks')], max_length=20, null=True),
        ),
    ]
