# Generated by Django 4.1.5 on 2023-04-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_employee_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='progress',
        ),
    ]
