# Generated by Django 4.1.5 on 2023-04-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_employee_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
