# Generated by Django 4.1.5 on 2023-04-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_employee_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
