# Generated by Django 4.1.5 on 2023-05-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_employee_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='agency',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='budg',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cert',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cont',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fund',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='progress',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proj_comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proj_stat',
            field=models.CharField(choices=[('Complete', 'Complete'), ('On-Going', 'On-Going'), ('Under Procurement', 'Under Procurement')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reco',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reg',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slip',
            field=models.CharField(choices=[('ANS', 'ANS'), ('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending'), ('Terminated', 'Terminated'), ('Blanks', 'Blanks')], max_length=1000, null=True),
        ),
    ]
