# Generated by Django 4.1.5 on 2023-05-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_usermodel_alter_employee_agency_alter_employee_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
